### ISSUE TITLE
blogdown 0.7 fails to place HTML from Rmd in public  

### ISSUE THREAD

**Issue by ConorIA** [rstudio/blogdown#312]
I was concerned that the posts that are written in Rmd are missing from my website (site: https://conr.ca; code: https://gitlab.com/ConorIA/conr_ca).* I use the rocker/tidyverse Docker image as base and install blogdown from CRAN before running `blogdown::build_site()`. 

I can reproduce the issue on my laptop with blogdown 0.7, as well as the current git commit. In the tree output below, my Rmd files all have a `_files` folder, but none of them have an `index.html` file. The other pages, those that _do_ have a corresponding `.html` file, were all vanilla markdown. 

On my server (with blogdown 0.6, this issue is not present; all files are present in `/public`.)

```
cd public/post && tree                                                                                       academic @ master|…7
.
├── 2017-09-19_bookmarklet
│   └── index.html
├── 2018-01-11_revisiting_december_temps_files
│   └── figure-html
│       ├── unnamed-chunk-3-1.png
│       ├── unnamed-chunk-5-1.png
│       └── unnamed-chunk-6-1.png
├── 2018-01-14_winter_polar_events_in_to_files
│   └── figure-html
│       └── unnamed-chunk-11-1.png
├── 2018-02-14_playing_with_bases
│   └── index.html
├── 2018-05-09-choosing-stations-in-peru-pt-1_files
├── 2018-05-22-choosing-stations-in-peru-pt-2_files
│   └── figure-html
│       └── unnamed-chunk-27-1.png
├── index.html
├── index.xml
├── installing-r-on-android-via-termux
│   └── index.html
└── page
    └── 1
        └── index.html
```

**EDIT**: ~~Might be related to #305. I haven't set the global option for draft. Is it on by default?~~
It would appear not. `Rscript -e "options(blogdown.draft.output = FALSE); blogdown::build_site()"` gave the same result.

 \* *Note: not missing anymore as I've rolled back to bookdown 0.6*

**Comment by yihui** [comment]
@ConorIA Ah. That was due to a careless omission of the `!` operator. Should be fixed now. Thanks for the report!

If you have to use the CRAN version, a hack to fix the issue is

```r
if (packageVersion('blogdown') == '0.7') options(blogdown.draft.output = TRUE)
```

@mwaldstein FYI, the implementation for #305 was buggy. You need to use the current dev version of **blogdown**.

**Comment by ConorIA** [comment]
Thanks, @yihui!

**Comment by yihui** [comment]
@DataStrategist Please always show me the source (either a Github repo or just plain-text code here in the Github issue) when you run into problems. I cannot magically read the source text behind screenshots: https://yihui.name/en/2018/01/screenshots-vs-text/

Anyway, from your Github profile, thsi might be what you were talking about: https://github.com/DataStrategist/amitkohli.com/commit/e48a6b5ba468cb6a8ad0e5e72e70492dc4dbc4a4 No need to GRRRRR :) You still have to listen to me: don't use the Knit button -- it just won't work: https://bookdown.org/yihui/blogdown/workflow.html

This particular issue reported by @ConorIA has been fixed. I don't think your new issue is still relevant to his. Let's move to https://github.com/rstudio/blogdown/issues/169#issuecomment-404535423.

**Comment by DataStrategist** [comment]
Sorry for not putting my github repo... won't happen again. How embarassing that you read my commit message!!! LOL!  It's just since I'm committing html, it's tough to see the changes so I'm actually working for work, and then on and off committing things here and feel like I"m going crazy doing the same thing three times!! :D Sorry, I'll try to not grrrrrrrrrrr. 

I know the knit won't work... I was more just checking that the code was fine locally. 

Moving to 169.

**Comment by GuangchuangYu** [comment]
hi yihui, the issue seems still exists.

here is [the repo](https://github.com/GuangchuangYu/software/tree/master/wChIPseeker) and the [output folder](https://github.com/GuangchuangYu/software/tree/master/docs/ChIPseeker). 

and here is my hugo version:

```
Hugo Static Site Generator v0.49.2/extended linux/amd64 BuildDate: unknown
```

**Comment by ConorIA** [comment]
@GuangchuangYu, excuse me if I'm misreading something in your repo, but are you building with your Makefile? The line `options(blogdown.draft.output = TRUE)` will prevent the RMD files from rendering.

**Comment by yihui** [comment]
Right. Don't do this: https://github.com/GuangchuangYu/software/commit/8bd164cd62748dda85a85803e21231e5d58ec363

**Comment by GuangchuangYu** [comment]
![screenshot_2018-10-29_09-06-46](https://user-images.githubusercontent.com/626539/47624688-0576a000-db5a-11e8-9965-d1e2d53686a3.png)

There is no effect without the option. Any idea?

**Comment by GuangchuangYu** [comment]
just come across with <https://github.com/digitalcraftsman/hugo-material-docs/issues/84>, and downgrade hugo to v 0.31 and everything works fine. :crying_cat_face:
