### ISSUE TITLE
The lastest blogdown convert relativeURL to absolute URL

### ISSUE THREAD

**Issue by ShixiangWang** [rstudio/blogdown#494]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

---

I just install the latest hugo and blogdown from GitHub, find that the `hugo_build` convert relativeURL to absoluteURL. The package works perfectly before, I don't know why.

```r
xfun::session_info('blogdown')
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.3.1093

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.15 bookdown_0.21    digest_0.6.26   
  evaluate_0.14    glue_1.4.2       graphics_4.0.2   grDevices_4.0.2  highr_0.8       
  htmltools_0.5.0  httpuv_1.5.4     jsonlite_1.7.1   knitr_1.30       later_1.1.0.1   
  magrittr_1.5     markdown_1.1     methods_4.0.2    mime_0.9         promises_1.1.1  
  R6_2.4.1         Rcpp_1.0.5       rlang_0.4.8      rmarkdown_2.4.6  servr_0.19      
  stats_4.0.2      stringi_1.5.3    stringr_1.4.0    tinytex_0.26     tools_4.0.2     
  utils_4.0.2      xfun_0.18        yaml_2.2.1      

Hugo version: 0.76.5
```

![image](https://user-images.githubusercontent.com/25057508/96364137-c0dfd700-116b-11eb-8171-39e4c5885866.png)

This is my [config.toml](https://github.com/ShixiangWang/home/blob/master/config.toml).

By the way, I have another question about lastest version of blogdown, it always auto-starts hugo preview site when I open RStudio and always report the following error which the version I used before works perfectly.

```
blogdown::serve_site()
Launching the server via the command:
  /Users/wsx/Library/Application Support/Hugo/0.76.5/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-ivy -D -F --navigateToChanged
Error: It took more than 30 seconds to launch the server. There may be something wrong. The process has been killed. If the site needs more time to be built and launched, set options(blogdown.server.timeout) to a larger value.
```

Best,

Shixiang

**Comment by ShixiangWang** [comment]
I just roll back to blogdown 0.20 and it works fun.

```
blogdown::serve_site()
Start building sites … 
WARN 2020/10/18 18:11:32 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
WARN 2020/10/18 18:11:32 Page.RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}

                   | EN   
-------------------+------
  Pages            | 503  
  Paginator pages  |   0  
  Non-page files   |  13  
  Static files     | 352  
  Processed images |   0  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 690 ms
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /Users/wsx/go/src/github.com/ShixiangWang/home at http://127.0.0.1:4321

> xfun::session_info("blogdown")
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.3.1093

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_0.20   bookdown_0.21   digest_0.6.26   evaluate_0.14  
  glue_1.4.2      graphics_4.0.2  grDevices_4.0.2 highr_0.8       htmltools_0.5.0 httpuv_1.5.4   
  jsonlite_1.7.1  knitr_1.30      later_1.1.0.1   magrittr_1.5    markdown_1.1    methods_4.0.2  
  mime_0.9        promises_1.1.1  R6_2.4.1        Rcpp_1.0.5      rlang_0.4.8     rmarkdown_2.4.6
  servr_0.19      stats_4.0.2     stringi_1.5.3   stringr_1.4.0   tinytex_0.26    tools_4.0.2    
  utils_4.0.2     xfun_0.18       yaml_2.2.1     
```

**Comment by tcgriffith** [comment]
rolling back is not a true solution

**Comment by yihui** [comment]
> I just install the latest hugo and blogdown from GitHub, find that the `hugo_build` convert relativeURL to absoluteURL. The package works perfectly before, I don't know why.

That's actually the correct behavior, and I don't think the behavior was changed from **blogdown** 0.20 to 0.21. You can try `blogdown::hugo_build()` with **blogdown** 0.20, and I'm reasonably sure it will generate the same results.

What was actually changed was that `serve_site()` in 0.21 no longer creates the `public/` directory by default (or in your case, the `docs/` directory).

If you need relative URLs, you have to set `baseURL = "/"` instead of `"https://shixiangwang.github.io/home/"` in your `config.toml`. Personally I don't recommend it, unless you fully understand the consequences.

> By the way, I have another question about latest version of blogdown, it always auto-starts hugo preview site when I open RStudio and always report the following error which the version I used before works perfectly.

Please follow the issue guide, which has told you to try the development version first. I've already fixed this issue a few days ago: a90ec8811f7d481c41d7680f3de1a27e668e156b

**Comment by ShixiangWang** [comment]
@yihui Thanks for your response. For the second question, I said that I installed the latest version of blogdown from GitHub today. You can see the version number from screenshot.

![image](https://user-images.githubusercontent.com/25057508/96371962-24cbc500-1197-11eb-8055-cd475b93d42e.png)

I just install the newest version again (from Github) and confirm that the issue still exists

```
> blogdown:::preview_site(startup = TRUE)
Launching the server via the command:
  /Users/wsx/Library/Application Support/Hugo/0.76.5/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-ivy -D -F --navigateToChanged
Error: It took more than 30 seconds to launch the server. There may be something wrong. The process has been killed. If the site needs more time to be built and launched, set options(blogdown.server.timeout) to a larger value.
> xfun::session_info("blogdown")
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.3.1093

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.15 bookdown_0.21    digest_0.6.26   
  evaluate_0.14    glue_1.4.2       graphics_4.0.2   grDevices_4.0.2  highr_0.8       
  htmltools_0.5.0  httpuv_1.5.4     jsonlite_1.7.1   knitr_1.30       later_1.1.0.1   
  magrittr_1.5     markdown_1.1     methods_4.0.2    mime_0.9         promises_1.1.1  
  R6_2.4.1         Rcpp_1.0.5       rlang_0.4.8      rmarkdown_2.4.6  servr_0.19      
  stats_4.0.2      stringi_1.5.3    stringr_1.4.0    tinytex_0.26     tools_4.0.2     
  utils_4.0.2      xfun_0.18        yaml_2.2.1      

Hugo version: 0.76.5
```

**Comment by yihui** [comment]
@ShixiangWang Sorry I missed that. I guess I know what's going on now, and will push a fix shortly. Thanks!

**Comment by yihui** [comment]
Should be fixed now. Thanks again for the report!

```r
remotes::install_github('rstudio/blogdown')
```

**Comment by ShixiangWang** [comment]
@yihui Yihui, it works now. Thanks 👍

**Comment by yihui** [comment]
While trying to fix #506, I also figured out an alternative fix to this issue. If you have a chance, I'd appreciate it if you could try the dev version:

```r
remotes::install_github('rstudio/blogdown')
```

Thanks!

**Comment by ShixiangWang** [comment]
@yihui Thanks, yihui. I will take a try and let you know soon.

**Comment by ShixiangWang** [comment]
It works :)

![image](https://user-images.githubusercontent.com/25057508/99687936-2bb06500-2ac0-11eb-82a4-3f574652b4fc.png)

**Comment by yihui** [comment]
Great! Thanks a lot for letting me know!
